export const metadata = {
  title: "Privacy Policy",
  keywords: ["privacy", "policy"],
}

const Privacy = () => {
  return (
    <div className="max-w-4xl mx-auto">
      <h1 className="heading">Privacy Policy</h1>
      <p className="mb-2">Last updated: February 18, 2024</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <h1 className="text-xl font-semibold highlight mt-5">Definitions</h1>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className="list-disc ml-4">
        <li>
          <p>
            <strong className="highlight font-semibold">Account</strong> means a
            unique account created for You to access our Service or parts of our
            Service.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">Company</strong>{" "}
            (referred to as either &quot;the Company&quot;, &quot;We&quot;,
            &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Ratan
            Bandhej, 1079, Apnanagar-1, Near Sejwala Matam, Bhuj - Kutchh.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">Country</strong> refers
            to: Gujarat, India
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">Device</strong> means
            any device that can access the Service such as a computer, a
            cellphone or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">Personal Data</strong>{" "}
            is any information that relates to an identified or identifiable
            individual.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">Service</strong> refers
            to the Website.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">
              Service Provider
            </strong>{" "}
            means any natural or legal person who processes the data on behalf
            of the Company. It refers to third-party companies or individuals
            employed by the Company to facilitate the Service, to provide the
            Service on behalf of the Company, to perform services related to the
            Service or to assist the Company in analyzing how the Service is
            used.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">Usage Data</strong>{" "}
            refers to data collected automatically, either generated by the use
            of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">Website</strong> refers
            to Ratan Bandhej, accessible from{" "}
            <a
              href="ratanbandhej.vercel.app"
              rel="external nofollow noopener"
              target="_blank"
            >
              ratanbandhej.vercel.app
            </a>
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">You</strong> means the
            individual accessing or using the Service, or the company, or other
            legal entity on behalf of which such individual is accessing or
            using the Service, as applicable.
          </p>
        </li>
      </ul>

      <h1 className="text-xl font-semibold highlight mt-5">
        Collecting and Using Your Personal Data
      </h1>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-disc ml-4">
        <li>
          <p>Email address</p>
        </li>
        <li>
          <p>First name and last name</p>
        </li>
        <li>
          <p>Phone number</p>
        </li>
        <li>
          <p>Address, State, Province, ZIP/Postal code, City</p>
        </li>
      </ul>
      <p>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>

      <h1 className="text-xl font-semibold highlight mt-5">
        Use of Your Personal Data
      </h1>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc ml-4">
        <li>
          <p>
            <strong className="highlight font-semibold">
              To provide and maintain our Service
            </strong>
            , including to monitor the usage of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">
              To manage Your Account:
            </strong>{" "}
            to manage Your registration as a user of the Service. The Personal
            Data You provide can give You access to different functionalities of
            the Service that are available to You as a registered user.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">To contact You:</strong>{" "}
            To contact You by email, telephone calls, SMS, or other equivalent
            forms of electronic communication, such as a mobile application's
            push notifications regarding updates or informative communications
            related to the functionalities, products or contracted services,
            including the security updates, when necessary or reasonable for
            their implementation.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">To provide You</strong>{" "}
            with news, special offers and general information about other goods,
            services and events which we offer that are similar to those that
            you have already purchased or enquired about unless You have opted
            not to receive such information.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">
              To manage Your requests:
            </strong>{" "}
            To attend and manage Your requests to Us.
          </p>
        </li>
        <li>
          <p>
            <strong className="highlight font-semibold">
              For other purposes
            </strong>
            : We may use Your information for other purposes, such as data
            analysis, identifying usage trends, determining the effectiveness of
            our promotional campaigns and to evaluate and improve our Service,
            products, services, marketing and your experience.
          </p>
        </li>
      </ul>

      <h1 className="text-xl font-semibold highlight mt-5">
        Security of Your Personal Data
      </h1>
      <p>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>
      <h1 className="text-xl font-semibold highlight mt-5">
        Children's Privacy
      </h1>
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </p>

      <h1 className="text-xl font-semibold highlight mt-5">
        Links to Other Websites
      </h1>
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>

      <h1 className="text-xl font-semibold highlight mt-5">Contact Us</h1>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc ml-4">
        <li>
          By email:{" "}
          <a
            className="border-b highlight font-semibold"
            href="mailto:ratanbandhejbhuj@gmail.com"
          >
            ratanbandhejbhuj@gmail.com
          </a>
        </li>
        <li>
          By visiting this page on our website:{" "}
          <a
            className="border-b highlight font-semibold"
            href="https://ratanbandhej.vercel.app/contact"
            rel="external nofollow noopener"
            target="_blank"
          >
            https://ratanbandhej.vercel.app/contact
          </a>
        </li>
        <li>
          By phone number:{" "}
          <a
            className="border-b highlight font-semibold"
            href="tel:+917778975752"
            rel="external nofollow noopener"
            target="_blank"
          >
            +91 7778975752
          </a>
        </li>
      </ul>
    </div>
  )
}

export default Privacy
