// Generated by Xata Codegen 0.28.0. Please do not edit.
import { buildClient } from "@xata.io/client"
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client"

const tables = [
  {
    name: "Orders",
    columns: [
      { name: "UserId", type: "string" },
      { name: "Username", type: "string" },
      { name: "E-Mail", type: "email" },
      { name: "Phone", type: "string" },
      { name: "Address", type: "text" },
      { name: "Color", type: "string" },
      { name: "ProductName", type: "string" },
      { name: "ProductId", type: "string" },
      { name: "ProductPrice", type: "string" },
    ],
  },
] as const

export type SchemaTables = typeof tables
export type InferredTypes = SchemaInference<SchemaTables>

export type Orders = InferredTypes["Orders"]
export type OrdersRecord = Orders & XataRecord

export type DatabaseSchema = {
  Orders: OrdersRecord
}

const DatabaseClient = buildClient()

const defaultOptions = {
  databaseURL:
    "https://Saad-Khatri-s-workspace-0qp24m.us-east-1.xata.sh/db/ratanbandhej",
}

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables)
  }
}

let instance: XataClient | undefined = undefined

export const getXataClient = () => {
  if (instance) return instance

  instance = new XataClient()
  return instance
}
